services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 5s

  web:
    build: .
    environment:
      DEBUG: False
      ENVIRONMENT: ${ENVIRONMENT}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

    # internal only; if using containerized nginx
    expose:
      - "8000"

    # enable if using host level nginx
    # ports:
    #   - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
    # remove if using host level nginx
    volumes:
      # Share collected static with Nginx
      - staticfiles:/app/project/staticfiles

  # remove if using host level nginx
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "8000:80"     # access via http://localhost:8000
    volumes:
      # Mount the Nginx config
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the same static volume at a path Nginx serves from
      - staticfiles:/staticfiles:ro

volumes:
  pgdata:
  staticfiles:    # remove if using host level nginx
